### PR TITLE
commit message

### PR DESCRIPTION
**Pull request by bahyusanciko**

### CODE REVIEW

**Comment by bahyusanciko** [comment]
oke

**Comment by AwanDex007** [comment]
om, boleh minta pencerahan error .env ci-tiket?

**Comment by bahyusanciko** [comment]
install composer nya , buat .env di folder application

**Comment by AwanDex007** [comment]
> install composer nya , buat .env di folder application

makasih om pencerahan nya

**Comment by bahyusanciko** [comment]
Oke bro , kirim aja ss nya kalo ada error biar gw fixed knp

**Comment by AwanDex007** [comment]
Screenshot 2022-04-27 at 12-33-21 https __localhost

masih error om, apa harus upgrade CI?

**Comment by bahyusanciko** [comment]
belajar soal composer deh https://www.jagoanhosting.com/blog/pengertian-composer/ 
jadi ini project butuh composer buat install library

**Pull request merged**
